name: Flip
baseurl: /flip
description: Fast and lightweight probability tools for a dataset and a data stream
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.0.5-SNAPSHOT
org: com.xxxnell
markdown: kramdown
